modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      fail_if_not_ssl: false
      ip_protocol_fallback: false
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      preferred_ip_protocol: ip4
      valid_status_codes: []
      method: GET
